name: ruBeta
main: ru.hpp.comp.main
version: 1.4
Author: [HappyWaffle]
commands:
    colours:
        description: Показывает все цветовые коды майнкрафта
        usage: /<command>
    pl:
        description: Кикает при попытке посмотреть плагины
        usage: /<command>
    plugins:
        description: Кикает при попытке посмотреть плагины
        usage: /<command>
    uptime:
        description: Показывает uptime сервера
        usage: /<command>
    crash:
        description: краш.
        usage: /<command>
    ptime:
        description: /ptime 
        usage: /ptime <day/night/dawn/reset>
        