name: ruBeta
main: ru.hpp.fly.fly
version: 1.4
Author: [HappyWaffle]
commands:
    colours:
        description: Показывает все цветовые коды майнкрафта
        usage: /<command>
    fly:
        description: Летать
        usage: /<command>
    land:
        description: Приземлиться
        usage: /<command>
    pl:
        description: Кикает при попытке посмотреть плагины
        usage: /<command>
    plugins:
        description: Кикает при попытке посмотреть плагины
        usage: /<command>
    uptime:
        description: Показывает uptime сервера
        usage: /<command>
    sapling:
        description: Ставит саженцы в поле
        usage: /<command>
    repair:
        description: Чинит.
        usage: /<command>
    crash:
        description: краш.
        usage: /<command>
permissions:
    fly.fly:
        description: Право на флай
    ru.speed:
        description: Право на /speed
        
        